import type { TreasureFragment } from "./types"

export const mockFragments: TreasureFragment[] = [
  {
    id: "frag-1",
    order: 1,
    unlocked: true,
    imageUrl: "/fragments/fragment-1.png",
    revealedText: "En el este, donde el sol nace, comienza tu viaje...",
    unlockedByLevel: "1-4",
  },
  {
    id: "frag-2",
    order: 2,
    unlocked: true,
    imageUrl: "/fragments/fragment-2.png",
    revealedText: "Cruza el puente de madera antigua...",
    unlockedByLevel: "1-8",
  },
  {
    id: "frag-3",
    order: 3,
    unlocked: true,
    imageUrl: "/fragments/fragment-3.png",
    revealedText: "La palmera solitaria guarda secretos...",
    unlockedByLevel: "1-12",
  },
  {
    id: "frag-4",
    order: 4,
    unlocked: false,
    imageUrl: "/fragments/fragment-4.png",
    revealedText: "Bajo la roca con forma de calavera...",
    unlockedByLevel: "2-4",
  },
  {
    id: "frag-5",
    order: 5,
    unlocked: false,
    imageUrl: "/fragments/fragment-5.png",
    revealedText: "El arrecife de coral esconde la entrada...",
    unlockedByLevel: "2-8",
  },
  {
    id: "frag-6",
    order: 6,
    unlocked: false,
    imageUrl: "/fragments/fragment-6.png",
    revealedText: "Tres pasos al norte desde el ancla oxidada...",
    unlockedByLevel: "2-12",
  },
  {
    id: "frag-7",
    order: 7,
    unlocked: false,
    imageUrl: "/fragments/fragment-7.png",
    revealedText: "La cueva susurra historias de oro...",
    unlockedByLevel: "3-4",
  },
  {
    id: "frag-8",
    order: 8,
    unlocked: false,
    imageUrl: "/fragments/fragment-8.png",
    revealedText: "Donde las olas besan la arena negra...",
    unlockedByLevel: "3-8",
  },
  {
    id: "frag-9",
    order: 9,
    unlocked: false,
    imageUrl: "/fragments/fragment-9.png",
    revealedText: "Las rocas gemelas apuntan al tesoro...",
    unlockedByLevel: "3-12",
  },
  {
    id: "frag-10",
    order: 10,
    unlocked: false,
    imageUrl: "/fragments/fragment-10.png",
    revealedText: "La brújula nunca miente, sigue el norte...",
    unlockedByLevel: "4-4",
  },
  {
    id: "frag-11",
    order: 11,
    unlocked: false,
    imageUrl: "/fragments/fragment-11.png",
    revealedText: "Donde el agua cae desde lo alto...",
    unlockedByLevel: "4-8",
  },
  {
    id: "frag-12",
    order: 12,
    unlocked: false,
    imageUrl: "/fragments/fragment-12.png",
    revealedText: "La cruz marca el camino, no el destino...",
    unlockedByLevel: "4-12",
  },
  {
    id: "frag-13",
    order: 13,
    unlocked: false,
    imageUrl: "/fragments/fragment-13.png",
    revealedText: "Bajo el arco de piedra milenaria...",
    unlockedByLevel: "5-4",
  },
  {
    id: "frag-14",
    order: 14,
    unlocked: false,
    imageUrl: "/fragments/fragment-14.png",
    revealedText: "La X marca el lugar exacto...",
    unlockedByLevel: "5-8",
  },
  {
    id: "frag-15",
    order: 15,
    unlocked: false,
    imageUrl: "/fragments/fragment-15.png",
    revealedText: "¡El cofre del tesoro espera al valiente navegante!",
    unlockedByLevel: "5-12",
  },
]
